import { useState } from 'react'
import reactLogo from './assets/react.svg'
import lyricBoostLogo from '/lyricBoostLogo.svg'
import './App.css'

import awsconfig from './aws-exports'; // This is generated by the Amplify CLI
import { Amplify } from 'aws-amplify';

 
Amplify.configure(awsconfig); 

import { Authenticator, Button, Heading } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

function App() {

  return (
    <Authenticator>
      {({ signOut, user }) => (
        user && (
          <>
            <div>
              <a href="/" target="_blank">
                <img src={lyricBoostLogo} className="logo" alt="Lyric Boost logo" />
              </a>
            </div>
            <h1>Lyric Boost</h1>
            <p className="read-the-docs"> 
              Blast through writer's block.
            </p>
            <div style={{ container: { margin: '50px' } }}>
              <Heading level={1}>Hello {user.username}</Heading>
              <Button onClick={signOut}>Sign out</Button>
            </div>
          </>
        )
      )}
    </Authenticator>
  )
}

export default App;
